### ISSUE TITLE
No way to set timeout for any request

### ISSUE THREAD

**Issue by idanci** [blatyo/page_rankr#42]
Some proxies are very slow. A request can take up to 2 minutes and then fail due to timeout.

**Comment by blatyo** [comment]
Individual trackers do have the ability to pass options directly to HTTParty [[1](https://github.com/blatyo/page_rankr/blob/master/lib/page_rankr/tracker.rb#L16)]. So, if HTTParty has an option for it, you can do it that way. You're correct that there is no way to do it with the group methods (`ranks`, etc) though. I'd happily accept a pull request for passing the options through and any extra gymnastics HTTParty needs to set timeouts.

**Comment by idanci** [comment]
I'll do it when I have some free time.
BTW How about switching to restclient?

**Comment by blatyo** [comment]
When I switched from Typhoeus, I evaluated a couple libraries. I believe the issue with restclient is that it doesn't allow per connection proxies. You could only do it at the global level. That behavior wouldn't work well with multiple threads and the proxy services.

I personally prefer Faraday these days, because of the ability to inject middleware to customize requests and responses.

I wouldn't be opposed to a switch, as long as it maintains feature parity with what's currently used and provides some notable benefit. If it's just switching for switching's sake, then I wouldn't accept it.
